<?php

// SPDX-FileCopyrightText: 2026 Touchpoint Contributors
// SPDX-License-Identifier: AGPL-3.0-or-later

declare(strict_types=1);

/**
 * Regenerates the AUTOGEN inventory block in docs/ARCHITECTURE.md from the live
 * source tree (routes, DB tables, migrations, and the file maps for the backend
 * and frontend). The prose around the block is hand-written and untouched.
 *
 * Run via `make docs` (or `php scripts/gen-docs.php`). CI runs this and fails if
 * the committed file drifts — so the factual half of the architecture doc can
 * never go stale without the build noticing.
 *
 * Exit codes: 0 ok; 1 missing markers / unreadable inputs.
 */

$root = dirname(__DIR__);
chdir($root);

const DOC = 'docs/ARCHITECTURE.md';
const START = '<!-- AUTOGEN:inventory START — generated by scripts/gen-docs.php; do not edit by hand -->';
const END = '<!-- AUTOGEN:inventory END -->';

/** @return string[] sorted repo-relative paths */
function rel(string $glob): array {
    $f = glob($glob) ?: [];
    sort($f);
    return $f;
}

function bnames(array $paths): string {
    if ($paths === []) {
        return '_(none)_';
    }
    return '`' . implode('`, `', array_map('basename', $paths)) . '`';
}

// ── version (source of truth: info.xml; package.json must match) ──────────────
$info = (string) @file_get_contents('appinfo/info.xml');
preg_match('#<version>([^<]+)</version>#', $info, $m);
$version = $m[1] ?? '?';
$pkg = json_decode((string) @file_get_contents('package.json'), true);
$pkgVersion = is_array($pkg) ? ($pkg['version'] ?? '?') : '?';
$versionLine = $version === $pkgVersion
    ? "**App version:** `$version` (info.xml and package.json in sync)."
    : "**App version:** ⚠️ info.xml=`$version` vs package.json=`$pkgVersion` — OUT OF SYNC.";

// ── HTTP routes ───────────────────────────────────────────────────────────────
$routesArr = require 'appinfo/routes.php';
$routeRows = [];
foreach (($routesArr['routes'] ?? []) as $r) {
    $routeRows[] = sprintf('| `%s` | `%s` | `%s` |', $r['verb'], '/' . ltrim($r['url'], '/'), $r['name']);
}

// ── DB tables (defined name; physical prefix oc_ added by Nextcloud) ──────────
$tables = [];
foreach (rel('lib/Migration/*.php') as $mig) {
    $src = (string) file_get_contents($mig);
    if (preg_match_all("#createTable\\('([^']+)'\\)#", $src, $mm)) {
        foreach ($mm[1] as $t) {
            $tables[$t] = basename($mig);
        }
    }
}
ksort($tables);
$tableRows = [];
foreach ($tables as $t => $mig) {
    $tableRows[] = sprintf('| `%s` (physical `oc_%s`) | `%s` |', $t, $t, $mig);
}

// ── file maps (categorised by role, not just by directory) ──────────────────
$controllers = rel('lib/Controller/*Controller.php');
$services = rel('lib/Service/*Service.php');
// Exceptions live next to the controllers/services that throw them.
$exceptions = rel('lib/*/*Exception.php');
sort($exceptions);
// Whatever is left in lib/Controller is a shared trait/helper (ErrorHandler,
// RequiresUser, …).
$ctrlHelpers = array_values(array_diff(rel('lib/Controller/*.php'), $controllers, $exceptions));
$mappers = rel('lib/Db/*Mapper.php');
$entities = array_values(array_diff(rel('lib/Db/*.php'), $mappers));

$inv = [];
$inv[] = START;
$inv[] = '';
$inv[] = '> Regenerate with `make docs` after any structural change. Do not hand-edit.';
$inv[] = '';
$inv[] = $versionLine;
$inv[] = '';
$inv[] = '### HTTP routes (`appinfo/routes.php`)';
$inv[] = '';
$inv[] = '| Verb | URL | Handler |';
$inv[] = '|---|---|---|';
$inv = array_merge($inv, $routeRows);
$inv[] = '';
$inv[] = '### Database tables';
$inv[] = '';
$inv[] = '| Table | Defined in |';
$inv[] = '|---|---|';
$inv = array_merge($inv, $tableRows);
$inv[] = '';
$inv[] = '### Source file map';
$inv[] = '';
$inv[] = '| Area | Files |';
$inv[] = '|---|---|';
$inv[] = '| Bootstrap | ' . bnames(rel('lib/AppInfo/*.php')) . ' |';
$inv[] = '| Controllers | ' . bnames($controllers) . ' |';
$inv[] = '| Controller traits/helpers | ' . bnames($ctrlHelpers) . ' |';
$inv[] = '| Services | ' . bnames($services) . ' |';
$inv[] = '| Exceptions | ' . bnames($exceptions) . ' |';
$inv[] = '| Mappers | ' . bnames($mappers) . ' |';
$inv[] = '| Entities | ' . bnames($entities) . ' |';
$inv[] = '| Migrations | ' . bnames(rel('lib/Migration/*.php')) . ' |';
$inv[] = '| Listeners | ' . bnames(rel('lib/Listener/*.php')) . ' |';
$inv[] = '| Search providers | ' . bnames(rel('lib/Search/*.php')) . ' |';
$inv[] = '| Notifiers | ' . bnames(rel('lib/Notification/*.php')) . ' |';
$inv[] = '| ContactsMenu | ' . bnames(rel('lib/ContactsMenu/*.php')) . ' |';
$inv[] = '| Dashboard widgets | ' . bnames(rel('lib/Dashboard/*.php')) . ' |';
$inv[] = '| Settings | ' . bnames(rel('lib/Settings/*.php')) . ' |';
$inv[] = '| Vue entries | ' . bnames(rel('src/*.js')) . ' |';
$inv[] = '| Vue components | ' . bnames(rel('src/components/*.vue')) . ' |';
$inv[] = '| Pinia stores | ' . bnames(rel('src/stores/*.js')) . ' |';
$inv[] = '| API clients | ' . bnames(rel('src/services/*.js')) . ' |';
$inv[] = '| Composables | ' . bnames(rel('src/composables/*.js')) . ' |';
$inv[] = '| Frontend utils | ' . bnames(rel('src/utils/*.js')) . ' |';
$inv[] = '';
$inv[] = END;
$block = implode("\n", $inv);

// ── splice into the doc between markers ──────────────────────────────────────
$doc = @file_get_contents(DOC);
if ($doc === false) {
    fwrite(STDERR, "error: cannot read " . DOC . "\n");
    exit(1);
}
$s = strpos($doc, START);
$e = strpos($doc, END);
if ($s === false || $e === false || $e < $s) {
    fwrite(STDERR, "error: AUTOGEN markers not found in " . DOC . "\n");
    exit(1);
}
$out = substr($doc, 0, $s) . $block . substr($doc, $e + strlen(END));

// --check: report drift without writing, ignoring any unrelated prose edits in
// the working tree (we only compare the generated block). CI uses this.
if (in_array('--check', $argv, true)) {
    if ($out !== $doc) {
        fwrite(STDERR, "error: " . DOC . " inventory is stale — run 'make docs' and commit.\n");
        exit(1);
    }
    fwrite(STDERR, DOC . " inventory is up to date\n");
    exit(0);
}

if ($out !== $doc) {
    file_put_contents(DOC, $out);
    fwrite(STDERR, "updated " . DOC . "\n");
} else {
    fwrite(STDERR, DOC . " already up to date\n");
}
exit(0);
